# Sops configuration for secrets encryption
keys:
  - &hbohlen_age age1... # Replace with actual Age public key

creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *hbohlen_age